root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./main.go"
bin = "./tmp/main"
full_bin = "./tmp/main"
log = "build-errors.log"
include_ext = ["go", "tpl", "tmpl", "html", "sql"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log_file = "air.log"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
time = true

[misc]
clean_on_exit = true
