[tool.poetry]
name = "megaservice"
version = "0.1.0"
description = ""
authors = ["pavittarx <29155477+pavittarx@users.noreply.github.com>"]
readme = "README.md"
package-mode=false

[tool.poetry.dependencies]
python = "^3.12"
opea-comps = "^1.2"
fastapi =">=0.115.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
