swagger: "2.0"
info:
  title: Language Portal API
  version: "1.0.0"
host: localhost:3000
basePath: "/api"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /health:
    get:
      responses:
        "200":
          description: Service is healthy

  /words:
    get:
      parameters:
        - name: page
          in: query
          type: integer
          default: 1
        - name: pageSize
          in: query
          type: integer
          default: 10
        - name: search
          in: query
          type: string
        - name: language
          in: query
          type: string
      responses:
        "200":
          schema:
            type: array
            items:
              $ref: "#/definitions/Word"
    post:
      parameters:
        - name: word
          in: body
          required: true
          schema:
            $ref: "#/definitions/Word"
      responses:
        "201":
          schema:
            $ref: "#/definitions/Word"

  /words/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        "200":
          schema:
            $ref: "#/definitions/Word"
    put:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - name: word
          in: body
          required: true
          schema:
            $ref: "#/definitions/Word"
      responses:
        "200":
          schema:
            $ref: "#/definitions/Word"
    delete:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        "204": {}

  /words/random:
    get:
      responses:
        "200":
          schema:
            $ref: "#/definitions/Word"

  /groups:
    get:
      parameters:
        - name: page
          in: query
          type: integer
          default: 1
        - name: pageSize
          in: query
          type: integer
          default: 10
        - name: search
          in: query
          type: string
      responses:
        "200":
          schema:
            type: array
            items:
              $ref: "#/definitions/Group"

  /sessions:
    get:
      parameters:
        - name: page
          in: query
          type: integer
          default: 1
        - name: pageSize
          in: query
          type: integer
          default: 10
      responses:
        "200":
          schema:
            type: array
            items:
              $ref: "#/definitions/Session"
    post:
      parameters:
        - name: session
          in: body
          required: true
          schema:
            $ref: "#/definitions/Session"
      responses:
        "201":
          schema:
            $ref: "#/definitions/Session"

  /study-activities:
    get:
      responses:
        "200":
          schema:
            type: array
            items:
              $ref: "#/definitions/StudyActivity"

definitions:
  Word:
    type: object
    properties:
      id:
        type: integer
      hindi:
        type: string
      english:
        type: string
      hinglish:
        type: string
      scrambled:
        type: string

  Group:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      description:
        type: string

  Session:
    type: object
    properties:
      id:
        type: integer
      activity_id:
        type: integer
      group_id:
        type: integer
      start_time:
        type: string
        format: date-time
      end_time:
        type: string
        format: date-time
      score:
        type: integer

  StudyActivity:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      description:
        type: string
      score:
        type: integer
